name: Generate xml sitemap

on:
  push:
    branches: [main]

jobs:
  sitemap_job:
    runs-on: ubuntu-latest
    name: Generate a sitemap

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1

      - name: Generate the sitemap
        id: sitemap
        uses: cicirello/generate-sitemap@v1
        with:
          base-url-path: https://johndellarosa.github.io/

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          title: "Automated sitemap update"
          body: >
            Sitemap updated by the [generate-sitemap](https://github.com/cicirello/generate-sitemap) 
            GitHub action. Automated pull-request generated by the 
            [create-pull-request](https://github.com/peter-evans/create-pull-request) GitHub action.

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
